function createfigures(tSim)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 08-Apr-2022 11:27:04

close all;

magForce = [0.45,0.5,0.75,1,1.5,2,2.25];
tExp = [2,1.5,0.8,0.65,0.5,0.35,0.25];
vExp = 0.0001./tExp;
vSim = 0.0001./tSim;

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(magForce,tSim,'.-');
plot2 = plot(magForce,tExp,'.-');
set(plot1,'DisplayName','Simulation');
set(plot2,'DisplayName','Real world Experimental Data');

% Create ylabel
ylabel('Time (s)');

% Create xlabel
xlabel('Magnetic Gradient (MA/m^2)');

% Create title
title('Time taken to travel 1mm for differing magnetic gradients');

box(axes1,'on');
grid(axes1,'on');
hold(axes1,'off');
% Create legend
legend(axes1,'show');


%Now Velocity
if(length(vSim) > 1)
    % Create figure
    figure2 = figure;
    % Create axes
    axes2 = axes('Parent',figure2);
    hold(axes2,'on');
    grid(axes2,'on');
    
    % Create multiple line objects using matrix input to plot
    plot3 = plot(magForce,vSim,'.-');
    plot4 = plot(magForce,vExp,'.-');
    set(plot3,'DisplayName','Simulation');
    set(plot4,'DisplayName','Real world Experimental Data');
    
    % Create ylabel
    ylabel('Velocity (m/s)');
    
    % Create xlabel
    xlabel('Magnetic Gradient (MA/m^2)');
    
    % Create title
    title('Velocity recorded at 1mm for differing magnetic gradients');
    
    box(axes2,'on');
    hold(axes2,'off');
    % Create legend
    legend(axes2,'Location','northwest');
end
