function createfiguresHaptic()
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 08-Apr-2022 11:27:04

close all;

%xParticleSize = [50, 75, 100, 125, 150, 175, 200];
xFlowBoth3 = [0.001, 0.0025, 0.005, 0.01, 0.015, 0.02, 0.025];
xFlow3v4 = [00.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05, 0.055, 0.06];
yFlowBoth3Old = [97.6,97.6,98, 97.2, 96.4, 85, 86.8];
yFlowBoth3New = [nan,nan,97.6, 99.8, 99.4, 94.2, 91.6];
yFlow3v43 = [97.6, 99.8, 99.4, 94.2, 91.6, 88.6, 93.6, 90.6, 81.4, 88.8, 82.8, 84.2];
yFlow3v44 = [95.2, 94, 92.4, 85.8, 90.2, 94, 86, 88.6, 87.2, 82.6, 84.8, 84];
SEFlowBoth3Old = [1.627540749, 1.423610434, 0.843274043, 0.742368582, 0.653197265, 2.816617357, 2.048305533];
SEFlowBoth3New = [nan,nan,0.305859643, 0.011407014, 0.0521744, 0.49549064, 1.706801392];
SEFlow3v43 = [0.305859643, 0.011407014, 0.0521744, 0.49549064, 1.706801392, 2.799650786, 1.102742979, 2.709925359, 8.548250324, 2.883085578, 1.594887863, 3.769194608];
SEFlow3v44 = [0.669658799, 1.264911064, 1.28133848, 6.087200214, 5.537842341, 2.691300136, 9.501541249, 2.314244735, 6.301345943, 5.085677535, 6.181357841, 6.866660062];



% SEParticleSize = [2.235073949, 0.777460253, 0.952190457, 1.783878421, 0.653197265, 0.426874949, 3.923717059];
% SEForceCap = [6.593262554, 10.56303828, 2.04504822, 2.851120637, 1.339983416];
% %SEStartDist1OLD = [0.742368582, 5.225578118, 5.019517462];
% SEStartDist = [1.1384199576606147, 0.25298221281346944, 0.06324555320336848, 1.7708754896942906;
%     0.12649110640673697, 0.12649110640673697, 0.06324555320336848, 1.0119288512538822;
%     1.0751744044572507, 0.18973665961010097, 1.2649110640673518, 1.8973665961010275;
%     0.6324555320336759, 0.06324555320336848, 2.782804340948173, 4.4904342774391;
%     1.7708754896942906, 1.8973665961010275, 5.375872022286245, 1.2649110640673518;
%     1.8973665961010275, 2.7195587877448046, 0.6957010852370443, 0.8854377448471453];
% SEStartDist05 = [0.8, 0, 2.640706976];
% SEStartDist1 = [1.146976702, 0.611010093, 2.441311123];
% SEStartDist15 = [2.733333333, 1.107549848, 3.058685266];
% SEStartDist2 = [1.406334874, 3.109841011, 3.474350459];
% SEOLDParticleSize = [4.592264026,2.274496281,3.903844259,3.550273855,3.967086812,3.396730454,3.043389923];
% SEOLDForceCap = [4.73,2.274496281,3.438345856,2.653299832,1.066666667];
% SEOLDFlow = [0.25,1,0.777460253,4.110150038,5.40945674,4.394440933,4.310710176];

% Create figure
figure1 = figure;
figure2 = figure;
% figure3 = figure;
% figure4 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');
axes2 = axes('Parent',figure2);
hold(axes2,'on');
% axes3 = axes('Parent',figure3);
% hold(axes3,'on');
% axes4 = axes('Parent',figure4);
% hold(axes4,'on');

plot1 = errorbar(axes1, xFlowBoth3, yFlowBoth3Old, SEFlowBoth3Old,'diamond--','MarkerSize',4,'MarkerEdgeColor','black','MarkerFaceColor','#ff3300');
plot2 = errorbar(axes1, xFlowBoth3, yFlowBoth3New, SEFlowBoth3New,'>:','MarkerSize',4,'MarkerEdgeColor','black','MarkerFaceColor','#008002');
plot3 = errorbar(axes2, xFlow3v4, yFlow3v43, SEFlow3v43,'<-.','MarkerSize',4,'MarkerEdgeColor','black','MarkerFaceColor','blue');
plot4 = errorbar(axes2, xFlow3v4, yFlow3v44, SEFlow3v44,'o-','MarkerSize',4,'MarkerEdgeColor','black','MarkerFaceColor','magenta');

 plot1.Color = 'black';
 plot2.Color = 'black';
 plot3.Color = 'black';
 plot4.Color = 'black';

% Create title
title(axes1,'Comparison of new flow implementation and old flow implementation');
title(axes2,'Effect of adding a fourth bifurcation in comparison to 3 bifurcations');

set(plot1,'DisplayName','Previous flow implementation');
set(plot2,'DisplayName','Newly implemented flow');
set(plot3,'DisplayName','3 bifurcations');
set(plot4,'DisplayName','4 bifurcations');
 

box(axes1,'on');
grid(axes1,'on');
% Create legend
legend(axes1,'show','Location','southeast');
box(axes2,'on');
grid(axes2,'on');
% Create legend
legend(axes2,'show','Location','southeast');

 % Create x and y labels
 xlabel(axes1,"Maximum Inlet Flow Velocity (m/s)");
 ylabel(axes1, 'Percentage of particles reaching goal state');
 ylim(axes1,[50,100]);
 xlabel(axes2,"Maximum Inlet Flow Velocity (m/s)");
 ylabel(axes2, 'Percentage of particles reaching goal state');
 ylim(axes2,[50,100]);


% Create multiple line objects using matrix input to plot
% plot5 = errorbar(axes1, xParticleSize, yOLDParticleSize, SEOLDParticleSize,'diamond-','MarkerSize',4,'MarkerEdgeColor','#808080','MarkerFaceColor','#ff3300');
% plot6 = errorbar(axes2, xForceCap, yOLDForceCap, SEOLDForceCap, 'diamond-','MarkerSize',4,'MarkerEdgeColor','#808080','MarkerFaceColor','#008002');
% plot7 = errorbar(axes3, xFlow, yOLDFlow, SEOLDFlow,'diamond-','MarkerSize',4,'MarkerEdgeColor','#808080','MarkerFaceColor','cyan');
% plot1 = errorbar(axes1, xParticleSize, yParticleSize, SEParticleSize,'o--','MarkerSize',4,'MarkerEdgeColor','black','MarkerFaceColor','blue');
% plot2 = errorbar(axes2, xForceCap, yForceCap, SEForceCap, 'o--','MarkerSize',4,'MarkerEdgeColor','black','MarkerFaceColor','magenta');
% plot3 = errorbar(axes3, xFlow, yFlow, SEFlow,'o--','MarkerSize',4,'MarkerEdgeColor','black','MarkerFaceColor','red');
%plot05 = errorbar(axes4, xStartDist-0.05, yStartDist05, SEStartDist05,'o','MarkerSize',4,'MarkerEdgeColor','black','MarkerFaceColor','red');
%plot10 = errorbar(axes4, xStartDist, yStartDist1, SEStartDist1,'square','MarkerSize',4,'MarkerEdgeColor','black','MarkerFaceColor','blue');
%plot15 = errorbar(axes4, xStartDist+0.05, yStartDist15, SEStartDist15,'<','MarkerSize',4,'MarkerEdgeColor','black','MarkerFaceColor','magenta');
%plot20 = errorbar(axes4, xStartDist+0.1, yStartDist2,SEStartDist2,'>','MarkerSize',4,'MarkerEdgeColor','black','MarkerFaceColor','cyan');
%plot05 = errorbar(axes4, xStartDistFlow, yStartDist(:,1), SEStartDist(:,1),'o--','MarkerSize',4,'MarkerEdgeColor','black','MarkerFaceColor','red');
%plot10 = errorbar(axes4, xStartDistFlow, yStartDist(:,2), SEStartDist(:,2),'square-','MarkerSize',4,'MarkerEdgeColor','black','MarkerFaceColor','blue');
%plot15 = errorbar(axes4, xStartDistFlow, yStartDist(:,3), SEStartDist(:,3),'<-.','MarkerSize',4,'MarkerEdgeColor','black','MarkerFaceColor','magenta');
%plot20 = errorbar(axes4, xStartDistFlow, yStartDist(:,4), SEStartDist(:,4),'>:','MarkerSize',4,'MarkerEdgeColor','black','MarkerFaceColor','#008002');
%barPlot05 = bar(axes4, xStartDistFlow, yflip,"stacked");
% newYStartDistTWO = yStartDist(:,[1,3]);
% newSESTARTDISTTWO = SEStartDist(:,[1,3]);
% barPlot05 = bar(axes4, xStartDistFlow.* 200, newYStartDistTWO,"grouped");
% hold on;
% barPlot05(1).FaceColor = 'red';
% barPlot05(2).FaceColor = 'blue';
% %barPlot05(3).FaceColor = 'magenta';
% %barPlot05(4).FaceColor = '#008002';
% 
% ngroups = size(newYStartDistTWO, 1);
% nbars = size(newYStartDistTWO, 2);
% % Calculating the width for each bar group
% groupwidth = min(0.8, nbars/(nbars + 1.5));
% for i = 1:nbars
%     x = (1:ngroups) - groupwidth/2 + (2*i-1) * groupwidth / (2*nbars);
%     errorbar(x, newYStartDistTWO(:,i), newSESTARTDISTTWO(:,i), '.','Color','black');
% end
% %plot05 = errorbar(axes4, xStartDistFlow, yStartDist(:,1), SEStartDist(:,1),'MarkerSize',4,'MarkerEdgeColor','black','MarkerFaceColor','red');
% %plot10 = errorbar(axes4, xStartDistFlow, yStartDist(:,2), SEStartDist(:,2),'MarkerSize',4,'MarkerEdgeColor','black','MarkerFaceColor','blue');
% %plot15 = errorbar(axes4, xStartDistFlow, yStartDist(:,3), SEStartDist(:,3),'MarkerSize',4,'MarkerEdgeColor','black','MarkerFaceColor','magenta');
% %plot20 = errorbar(axes4, xStartDistFlow, yStartDist(:,4), SEStartDist(:,4),'MarkerSize',4,'MarkerEdgeColor','black','MarkerFaceColor','#008002');
% %plot05.LineStyle = "none";
% %plot10.LineStyle = "none";
% %plot15.LineStyle = "none";
% %plot20.LineStyle = "none";
% 
% plot1.Color = 'black';
% plot2.Color = 'black';
% plot3.Color = 'black';
% %plot05.Color = 'red';
% %plot10.Color = 'blue';
% %plot15.Color = 'magenta';
% %plot20.Color = "#008002";
% %plot05.Color = 'red';
% %plot10.Color = 'blue';
% %plot15.Color = 'magenta';
% %plot20.Color = 'cyan';
% plot5.Color = '#808080';
% plot6.Color = '#808080';
% plot7.Color = '#808080';
% set(plot1,'DisplayName','Novint Falcon haptic device based control');%Effect of particle chain length on particle control
% set(plot2,'DisplayName','Novint Falcon haptic device based control');
% set(plot3,'DisplayName','Novint Falcon haptic device based control');
% 
% set(barPlot05(1),'DisplayName','Particles start in a "Clump" formation');
% set(barPlot05(2),'DisplayName','Particles start in a "Split" formation');
% %set(barPlot05(2),'DisplayName','Particles start in a "Spread" formation');
% %set(barPlot05(3),'DisplayName','Particles start in a "Split Clump" formation');
% %set(barPlot05(4),'DisplayName','Particles start in a "Split Spread" formation');
% %set(plot05,'DisplayName','Fluid Flow of 0.5 m/s');
% %set(plot10,'DisplayName','Fluid Flow of 1 m/s');
% %set(plot15,'DisplayName','Fluid Flow of 1.5 m/s');
% %set(plot20,'DisplayName','Fluid Flow of 2 m/s');
% 
% set(plot5,'DisplayName','Keyboard based control');
% set(plot6,'DisplayName','Keyboard based control');
% set(plot7,'DisplayName','Keyboard based control');
% 
% % Create x and y labels
% xlabel(axes1,"Length of particle chain in whole particles");
% ylabel(axes1, 'Percentage of particles reaching goal state');
% ylim(axes1,[0,100]);
% xlabel(axes2,"Maximum magnetic field gradient (MA/m^2)");
% ylabel(axes2, 'Percentage of particles reaching goal state');
% ylim(axes2,[0,100]);
% xlabel(axes3,"Rate of simulated blood-flow (m/s)");
% ylabel(axes3, 'Percentage of particles reaching goal state');
% ylim(axes3,[0,100]);
% xlabel(axes4,"Fluid Flow (m/s)");
% ylabel(axes4, 'Percentage of particles reaching goal state');
% ylim(axes4,[50,100]);
% % Create title
% title(axes1,'Effect of particle chain length on particle control');
% title(axes2,'Effect of capping the magnetic force on particle control');
% title(axes3,'Effect of flow rate on percentage on particle control');
% title(axes4,'Effect of starting distribution on particle control');
% 
% 
% box(axes1,'on');
% grid(axes1,'on');
% % Create legend
% legend(axes1,'show','Location','southeast');
% box(axes2,'on');
% grid(axes2,'on');
% % Create legend
% legend(axes2,'show','Location','southeast');
% box(axes3,'on');
% grid(axes3,'on');
% % Create legend
% legend(axes3,'show','Location','southwest');
% 
% legend(axes4,'Particles start in a "Clump" formation','Particles start in a "Split" formation','Location','southwest'); %Spread" formation','Particles start in a "Split Clump" formation','Particles start in a "Split Spread" formation','','','',''
% %axes4.XAxis.TickLabels = categorical(["Clump","Line","Split"]);
% %axes4.XAxis.TickLabels = categorical(["0.005","0.01","0.015","0.02","0.025","0.03"]);
% %axes4.XAxis.TickLabels = [0.005,"",0.01,"",0.015,"",0.02,"",0.025,"",0.03];
% axes4.XAxis.TickLabels = [0.005,0.01,0.015,0.02,0.025,0.03];
% %axes4.XAxis.TickValues = [0.005,0.01,0.015,0.02,0.025,0.03];
% %axes4.XAxis.TickLabels = [0.005,0.01,0.015,0.02,0.025,0.03];
% box(axes4,'on');
% grid(axes4,'on');

