t = timer('ExecutionMode', 'fixedRate', ...
          'Period', 0.1, ...
          'TasksToExecute', 200, ... 
          'TimerFcn', @(~,~) fprintf('(X, Y) = (%g, %g)\n', get(0, 'PointerLocation') * 1.5));
start(t);