function plotResultsMAR233DTimeBased()
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 08-Apr-2022 11:27:04

close all;

x = 60:60:360;


yBENClump(1,:,:) = [11.1 0 0 0 500 0
13.25 0 0 0 500 0
12.05 0 0 0 500 0
11.75 0 0 23 477 0
11.25 0 0 0 500 0
11.3 0 0 0 500 0
15 0 0 7 146 0
11.95 0 0 0 473 0
12.45 0 0 0 500 0
11.3 0 0 0 500 0];

yBENClump(2,:,:) = [9.9 7 0 3 144 346
10 0 0 1 499 0
12.45 1 0 5 494 0
15 0 0 0 122 4
11 1 0 0 499 0
9.3 0 0 0 500 0
9.6 5 0 16 479 0
12.3 0 4 2 494 0
9 0 0 0 500 0
11.7 0 1 0 498 0];


yBENClump(3,:,:) = [9.475 2 14 0 360 123
11.8 0 0 3 482 0
8.25 0 0 1 493 0
10.325 25 0 7 435 33
10.65 1 0 11 488 0
10.1 3 0 10 480 7
9.25 0 0 2 498 0
12.025 0 17 18 457 0
10.15 11 20 2 426 28
7.7 5 0 4 470 21];

yBENClump(4,:,:) = [8.55 0 0 14 405 81
9.65 21 14 4 369 73
6.625 3 0 23 362 109
7.4 5 12 12 379 92
7.725 1 0 19 390 90
9.9 6 3 7 407 77
8.325 3 1 7 443 46
7.175 1 76 22 297 104
8.925 20 4 26 349 95
6.9 31 3 5 372 89
];

yBENClump(5,:,:) = [9.25 3 1 24 179 163
7.875 45 1 3 306 145
9.95 48 1 3 222 121
9.45 12 0 16 345 122
9.9875 1 0 0 353 137
9.95 21 9 14 216 122
6.05 32 1 21 292 154
8.4875 25 4 39 262 170
9.4375 14 1 12 336 137
9.35 1 2 3 124 188];

yBENClump(6,:,:) = [9.775 45 2 9 322 118
9.225 46 4 6 205 168
5.2375 24 3 7 327 139
4.9625 16 4 18 280 182
9.8875 19 7 11 183 187
5.775 52 1 31 248 168
8 8 15 15 293 169
9.85 30 0 8 273 175
5.4625 30 0 15 318 137
9.3875 5 2 19 252 157];

%---------------------------------------------------------------------

yCombClump{1} = [13.75 0 0 0 500 0
14 0 0 0 401 99
14.6 0 0 0 500 0
15 6 0 0 29 13
11.3 0 0 0 500 0
11.7 0 0 0 500 0
12.05 0 0 0 500 0
14.45 0 0 0 136 0
10.8 0 0 0 500 0
15 0 0 1 418 81
12.9 0 0 0 500 0
13.9 0 0 0 500 0
12.65 0 0 0 500 0
15 0 0 0 480 20
13.8 0 0 0 360 0
12.4 0 0 0 307 0
14.35 0 0 0 500 0
13.25 0 0 33 15 0
12.9 0 0 0 500 0
14.8 0 0 0 447 53
13.95 0 0 0 486 0
13.25 0 0 0 500 0
12.45 0 0 0 500 0
12.35 0 0 0 500 0
13.85 13 0 3 202 253
13.9 0 0 0 244 250
12.55 0 5 0 495 0
14.55 0 0 0 500 0
15 21 0 24 170 14
13.35 0 0 0 500 0
14.1 0 0 0 498 0
12.9 0 0 0 452 48
15 0 0 0 391 3
13.9 0 0 1 499 0
12.9 0 0 1 485 0
12.35 0 0 0 500 0
13.65 0 0 4 496 0
15 0 0 25 139 0
12.55 0 0 0 458 0
13.65 0 0 0 500 0
12.35 0 0 0 500 0];
yCombClump{2} = [10.5 20 0 0 202 278
9.5 0 0 0 115 385
9.65 4 0 0 496 0
12.05 18 0 2 479 0
9.45 2 0 20 472 5
11.05 139 0 0 361 0
9.65 0 0 0 138 360
9.4 0 0 0 500 0
9.6 37 0 0 436 27
10.35 0 0 0 124 376
15 0 0 0 0 500
11.2 0 0 0 500 0
9.7 0 0 0 18 482
10.85 10 0 0 140 350
11.45 114 4 0 379 1
10.15 38 0 0 462 0
10.25 203 0 0 295 2
10.05 47 0 0 431 22
11.225 27 1 7 461 2
12.025 0 0 2 261 0
13.15 27 45 0 48 28
8.375 111 6 16 366 0
11.15 169 0 0 319 9
8.75 164 0 0 198 138
11.8 106 0 0 211 183
10.775 308 0 2 165 10
9.225 133 4 0 354 9
10.25 140 0 0 360 0
12 96 0 17 386 0
8.725 89 1 0 280 130
13.2 0 0 0 500 0
15 71 0 0 429 0
11.6 236 0 1 259 3
9.1 0 0 0 279 221
11.9 0 0 10 411 44
9.15 0 0 0 500 0
9.8 0 0 0 317 183
12.025 12 1 14 473 0
9.8 7 0 0 493 0
12.75 1 0 0 499 0
9.15 4 2 4 384 106
10.075 45 2 0 348 105
9.65 2 0 0 498 0
9.85 12 21 16 439 12
9.6 0 0 0 500 0
9.55 243 0 14 236 7
9.25 3 3 0 439 55
9.9 0 0 0 500 0
14.9 3 0 1 406 0];
yCombClump{3} = [11 2 85 4 109 30
11.225 5 0 0 202 293
9.275 6 23 23 303 144
7.8 123 1 0 376 0
11.85 9 31 14 33 248
6.775 33 0 0 190 277
10.95 87 0 0 324 89
9.6 93 2 10 395 0
10 88 7 0 248 99
11.825 1 3 44 382 70
7.025 7 2 3 110 373
9.9375 115 1 0 172 180
10.5 2 32 1 148 248
9.9125 3 0 1 326 170
12.025 10 2 0 448 0
8.725 41 2 14 158 280
7.625 0 2 1 101 396
9.7 33 8 19 99 305
11.45 114 4 0 379 1
8.5 23 28 0 448 1
9.9875 154 5 3 151 101
10.05 47 0 0 431 22
12.025 0 0 2 261 0
8.375 111 6 16 366 0
6.675 96 39 2 191 172
9.6 242 29 5 125 79
11 0 5 0 242 69
9.8875 36 1 6 287 167
9.9875 101 3 11 228 87
12 96 0 17 386 0
8.725 89 1 0 280 130
6.325 203 7 3 190 97
6.2 115 2 2 256 110
8.25 25 0 3 171 301
10.35 29 9 0 252 210
7.9 59 168 0 262 11
6.0375 84 1 2 215 198
7.825 9 46 119 323 3
9.8 0 0 0 317 183
11.225 100 0 0 392 0
9.15 4 2 4 384 106
10.075 45 2 0 348 105
9.05 184 41 0 121 140
9.85 12 21 16 439 12
9.9 5 73 2 185 153
8.6 0 87 2 408 3
9.375 105 1 3 159 165
8.2 115 64 7 314 0
6.0125 37 3 38 186 236
6.2375 6 4 0 387 103
11.8 190 0 2 286 0];
yCombClump{4} = [10.25 49 1 0 127 323
7.55 0 0 0 175 325
7.55 43 21 15 91 330
8.325 26 0 1 133 340
6.775 0 22 0 138 340
6.675 39 9 0 141 311
7.6 36 241 0 165 58
11.825 32 1 0 293 123
7.775 84 111 1 230 74
6.9 43 2 0 150 305
8.775 23 0 0 186 291
9.675 55 4 0 86 355
9.825 42 0 0 81 376
7.325 228 2 0 183 87
7.25 75 0 1 75 349
7.825 3 170 8 169 150
7.2 3 138 0 170 187
11.975 42 99 2 229 113
7.425 219 0 0 202 79
10.175 5 75 6 285 129
8.3 0 8 0 343 149
6.875 24 125 0 219 131
11.7 3 0 0 196 292
11.95 169 37 2 188 98
6.35 47 122 1 198 132
7.35 3 6 0 152 339
9.9 42 287 9 62 97];
yCombClump{5} = [6.0625 5 1 0 174 320
9.2125 205 106 7 53 127
9.05 0 1 0 150 329
6.4375 64 63 17 190 163
6.3 40 5 1 244 208
9.75 13 0 25 141 321
6.775 33 0 0 190 277
9.975 102 0 1 244 137
10 42 17 1 261 170
6.1375 20 35 5 207 233
10 72 47 4 115 219
6.625 50 58 33 126 233
6.4375 69 8 3 258 162
8.8625 19 33 21 117 196
8.725 41 2 14 158 280
9.7 33 8 19 99 305
10 144 60 1 156 132
8.5375 21 2 1 129 202
6.675 96 39 2 191 172
9.8875 36 1 6 287 167
9.875 56 21 0 212 149
6.2 115 2 2 256 110
8.25 25 0 3 171 301
8.375 64 89 22 166 159
6.0375 84 1 2 215 198
7.3 163 126 8 76 126
5.75 75 58 18 205 144
9.375 105 1 3 159 165
6.0125 37 3 38 186 236];
yCombClump{6} = [4.8875 1 99 0 66 334
7.7625 13 0 3 165 319
5.3625 11 0 15 131 343
6.6375 79 44 1 274 102
4.925 10 0 6 125 323
9.6625 35 9 4 136 212
9.525 53 67 6 54 246
8.775 69 35 0 219 154
9.5875 98 31 11 103 178
9.975 14 0 1 229 156
6.275 21 14 1 219 245
9.7625 40 4 1 295 152
6.0875 13 0 0 169 318
6.2 4 0 60 95 339
7.8125 16 6 4 128 319
9.4875 46 49 2 98 291
9.9625 48 26 1 148 179
6.7 32 3 5 147 313
7.95 86 100 1 108 205
5.525 18 64 16 250 151
6.825 92 4 0 211 192
8.8625 136 7 3 251 101
7.75 198 0 27 128 147
5.3875 51 131 16 141 161
9.7375 149 68 0 151 132
6.525 53 3 5 253 180
5.6625 108 3 2 218 169
5.5375 50 75 61 126 186];

%fgf = figure;
%axes1 = axes('Parent',fgf);
%hold(axes1,'on');
drawData = yCombClump;
for(i = 1:size(drawData,2))
    flowVel = i*60;
    x1 = repmat([flowVel,flowVel,flowVel,flowVel,flowVel],size(drawData{i},1),1);
    y1 = squeeze(repmat(drawData{i}(:,1),1,size(drawData{i},2)-1));
    z1 = squeeze(drawData{i}(:,2:6));
    plotdata = plot3(x1,y1,z1,'.','MarkerSize',10);
    hold on;
   % set(plotdata(1),'Color',"red");

    set(plotdata(1),'Color','blue');
    set(plotdata(2),'Color','red');
    set(plotdata(3),'Color','yellow');
    set(plotdata(4),'Color','magenta');
    set(plotdata(5),'Color','green');
end

    xlabel( "Maximum fluid flow velocity (mm/s)");
    ylabel("Time taken to reach the goal states (s)");
    zlabel("Percentage of particles reaching each goal state");
    xlim([60,360]);
    ylim([0,15]);
   % zlim([0,100]);
    xticks(60:60:360);
    grid("on");
    legend(["Goal 1", "Goal 2", "Goal 3", "Goal 4", "Goal 5"],"Location","northeast");

%yBENClump = yBENClump./5;
%yBENSplit = yBENSplit./5;

%yBENClumpSummed = cumsum(yBENClump,2);
%yBENSplitSummed = cumsum(yBENSplit,2);

%More Experiment Data:
yExperimentClump{1} = [0 0.45454545454545453 0.36363636363636365 487.1818181818182 0.2727272727272727;
12.333333333333334 5 0 364 84.22222222222223;
48.27272727272727 32.09090909090909 14 307.3636363636364 76.0909090909091;
47.142857142857146 139.71428571428572 3.857142857142857 176.57142857142858 129.71428571428572;
73.77777777777777 54.888888888888886 11.555555555555555 145.11111111111111 173.33333333333334;
56.5 64.125 19.5 139.875 205.5];

yExperimentSplit{1} = [0 0 0.25 439.75 7.625;
34.81818181818182 0 0.7272727272727273 459.27272727272725 4.636363636363637;
13.25 103.375 10.375 274 69.875;
39.84615384615385 124 4.384615384615385 221.69230769230768 95.07692307692308;
95.61538461538461 60.69230769230769 18.923076923076923 205.46153846153845 78.84615384615384;
116.08333333333333 98.83333333333333 15 126.58333333333333 85.83333333333333];

yExperimentClump{2} = [0 0.7 3.4 447 2;
50 0 0.3 336.5 104.2;
51.8 3.6 4 360.7 55.9;
65.3 9.5 0.7 178.9 244.6;
60.5 5.7 8.9 191.8 221.1;
68.2 4 4.8 189 230.3];

yExperimentSplit{2} = [3.4 0 6.2 357 69.9;
120.3 0 0.4 335.8 31.7;
132.9 0.9 4.7 330.1 27;
124.6 14.6 1.5 209.4 119.3;
110.1 17 2.5 213.3 120.9;
143.9 8.1 8.7 202.8 109];

yExperimentClump{3} = [0 0.1 0 440.2 9.7;
1.2 0.4 5 411 82.2;
11.7 37.6 9.3 348.1 92.8;
33 82.2 1.7 163.3 213.6;
52.6 35.1 13.1 171.2 204.9;
54.6 39.8 22.4 156.3 186.8];

yExperimentSplit{3} = [13.2 13.7 0.4 448.9 6.5;
13.7 16.6 3.5 406.1 46.3;
27.3 71.9 7.3 328.1 59;
38.9 61.8 18.9 248.5 121.4;
64.9 54.6 38.5 213 96.8;
69.3 77 23.9 210.7 97.4];

yExperimentClump{4} = [0.6 0 0 412.2 11.2;
18.3 0 2.2 338.8 140.4;
33.9 15.6 7.3 256.4 135.1;
35.2 40.8 1.7 164.7 252.9;
56 23.6 6 192.2 217;
41 28.9 8.1 163.8 220];

yExperimentSplit{4} = [0 0.1 0.8 383.6 13.3;
117.3 0 1.5 343.7 35.3;
97.7 9.7 1.7 304 38.5;
68.1 63.4 0.5 242.7 104.7;
106.7 25.3 3.1 251.2 86.9;
122.3 43 6.5 187.3 114.4];

%THIS ONE IS COMBINED
yExperimentClump{5} = [0.975609756097561 0.2926829268292683 2.4390243902439024 427.3414634146341 20.341463414634145;
53.89795918367347 1.836734693877551 2.2857142857142856 345.6530612244898 82.3061224489796;
60.666666666666664 15.137254901960784 7.470588235294118 266.72549019607845 120.92156862745098;
49.44444444444444 54.851851851851855 1.8888888888888888 173.03703703703704 217.88888888888889;
63.06896551724138 27.137931034482758 8.724137931034482 177.44827586206895 204.86206896551724;
55.142857142857146 30.071428571428573 10.178571428571429 165.96428571428572 219.53571428571428];

yExperimentSplit{5} = [36.1875 0.020833333333333332 1.6458333333333333 367.6458333333333 46.916666666666664;
91.33333333333333 4.7254901960784315 0.9607843137254902 308.4313725490196 85.49019607843137;
94.4375 21.958333333333332 5.875 259.3958333333333 95.97916666666667;
74.0909090909091 72.48484848484848 2.3333333333333335 224.33333333333334 105.33333333333333;
103.36363636363636 36.72727272727273 9.151515151515152 221.6969696969697 94.03030303030303;
126.71875 53.03125 10.375 169.375 102];



%Now draw the data:

% Create figure
figure1 = figure;
figure2 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');
axes2 = axes('Parent',figure2);
hold(axes2,'on');

plot1 = plot(axes1,x,yBENClump, '.-','MarkerSize',4,'MarkerFaceColor','#ff3300');
plot2 = plot(axes2,x,yBENSplit, '.-','MarkerSize',4,'MarkerFaceColor','#ff3300');

set(plot1(1),'DisplayName','Goal 1');
set(plot1(2),'DisplayName','Goal 2');
set(plot1(3),'DisplayName','Goal 3');
set(plot1(4),'DisplayName','Goal 4');
set(plot1(5),'DisplayName','Goal 5');
xlabel(axes1,"Maximum Fluid Velocity (mm/s)");
ylabel(axes1, 'Percentage of particles reaching each goal state');
title(axes1,'Percentage of particles reaching each goal state for different fluid velocities starting in a clump formation');
box(axes1,'on');
grid(axes1,'on');
legend(axes1,'show','Location','northeast');

set(plot2(1),'DisplayName','Goal 1');
set(plot2(2),'DisplayName','Goal 2');
set(plot2(3),'DisplayName','Goal 3');
set(plot2(4),'DisplayName','Goal 4');
set(plot2(5),'DisplayName','Goal 5');
xlabel(axes2,"Maximum Fluid Velocity (mm/s)");
ylabel(axes2, 'Percentage of particles reaching each goal state');
title(axes2,'Percentage of particles reaching each goal state for different fluid velocities starting in a split formation');
box(axes2,'on');
grid(axes2,'on');
legend(axes2,'show','Location','northeast');


 for(i = 1:size(yExperimentClump,2))
    % Create figure
    figureClumpNew = figure; 
    figureSplitNew = figure;

    %Create axes
    axesClumpNew = axes('Parent',figureClumpNew);
    hold(axesClumpNew,'on');
    axesSplitNew = axes('Parent',figureSplitNew);
    hold(axesSplitNew,'on');


    if(true)

        %Both bar charts
        barPlotClump = bar(axesClumpNew, x-12.5, yExperimentClump{i}./5,0.4, "stacked");
        barPlotSplit = bar(axesSplitNew, x-12.5, yExperimentSplit{i}./5,0.4, "stacked");
        barPlotClumpB = bar(axesClumpNew, x+12.5, yBENClump,0.4, "stacked");
        barPlotSplitB = bar(axesSplitNew, x+12.5, yBENSplit,0.4, "stacked");
        set(barPlotClumpB(1),'FaceColor','blue');
        set(barPlotClumpB(2),'FaceColor','red');
        set(barPlotClumpB(3),'FaceColor','yellow');
        set(barPlotClumpB(4),'FaceColor','magenta');
        set(barPlotClumpB(5),'FaceColor','green');
        set(barPlotSplitB(1),'FaceColor','blue');
        set(barPlotSplitB(2),'FaceColor','red');
        set(barPlotSplitB(3),'FaceColor','yellow');
        set(barPlotSplitB(4),'FaceColor','magenta');
        set(barPlotSplitB(5),'FaceColor','green');
        hold on;

        set(barPlotClump(1),'DisplayName','Goal 1');
        set(barPlotClump(2),'DisplayName','Goal 2');
        set(barPlotClump(3),'DisplayName','Goal 3');
        set(barPlotClump(4),'DisplayName','Goal 4');
        set(barPlotClump(5),'DisplayName','Goal 5');
        set(barPlotSplit(1),'DisplayName','Goal 1');
        set(barPlotSplit(2),'DisplayName','Goal 2');
        set(barPlotSplit(3),'DisplayName','Goal 3');
        set(barPlotSplit(4),'DisplayName','Goal 4');
        set(barPlotSplit(5),'DisplayName','Goal 5');
        set(barPlotClumpB(1),'DisplayName','Goal 1 (Ex)');
        set(barPlotClumpB(2),'DisplayName','Goal 2 (Ex)');
        set(barPlotClumpB(3),'DisplayName','Goal 3 (Ex)');
        set(barPlotClumpB(4),'DisplayName','Goal 4 (Ex)');
        set(barPlotClumpB(5),'DisplayName','Goal 5 (Ex)');
        set(barPlotSplitB(1),'DisplayName','Goal 1 (Ex)');
        set(barPlotSplitB(2),'DisplayName','Goal 2 (Ex)');
        set(barPlotSplitB(3),'DisplayName','Goal 3 (Ex)');
        set(barPlotSplitB(4),'DisplayName','Goal 4 (Ex)');
        set(barPlotSplitB(5),'DisplayName','Goal 5 (Ex)');

        xlabel(axesClumpNew,"Maximum Fluid Velocity (mm/s)");
        ylabel(axesClumpNew, 'Percentage of particles reaching each goal state');
        title(axesClumpNew,'Percentage of particles reaching each goal state for different fluid velocities starting in a clump formation');
        box(axesClumpNew,'on');
        grid(axesClumpNew,'on');
        legend(axesClumpNew,'show','Location','southwest');

        xlabel(axesSplitNew,"Maximum Fluid Velocity (mm/s)");
        ylabel(axesSplitNew, 'Percentage of particles reaching each goal state');
        title(axesSplitNew,'Percentage of particles reaching each goal state for different fluid velocities starting in a split formation');
        box(axesSplitNew,'on');
        grid(axesSplitNew,'on');
        legend(axesSplitNew,'show','Location','southwest');
    else
        if(true)
            barPlotClump = bar(axesClumpNew, x, yExperimentClump{i}./5, "stacked");
            barPlotSplit = bar(axesSplitNew, x, yExperimentSplit{i}./5, "stacked");
            plotBenClumpCumulative = plot(axesClumpNew,x,yBENClumpSummed, '.-','MarkerSize',4,'MarkerFaceColor','#ff3300');
            plotBenSplitCumulative = plot(axesSplitNew,x,yBENSplitSummed, '.-','MarkerSize',4,'MarkerFaceColor','#ff3300');
        else
        %plot
        plotNewClump = plot(axesClumpNew,x,yExperimentClump{i}./5, '.-','MarkerSize',4,'MarkerFaceColor','green');
        xlabel(axesClumpNew,"Maximum Fluid Velocity (mm/s)");
        ylabel(axesClumpNew, 'Percentage of total particles reaching each goal state');
        ylim(axesClumpNew,[0,100]);
        title(axesClumpNew,'Percentage of total particles reaching each goal state for different fluid velocities with user control starting in clump formation');
        box(axesClumpNew,'on');
        grid(axesClumpNew,'on');
        legend(axesClumpNew,["Goal 1", "Goal 2", "Goal 3", "Goal 4", "Goal 5"],'Location','northwest');
    
        plotNewSplit = plot(axesSplitNew,x,yExperimentSplit{i}./5, '.-','MarkerSize',4,'MarkerFaceColor','green');
        xlabel(axesSplitNew,"Maximum Fluid Velocity (mm/s)");
        ylabel(axesSplitNew, 'Percentage of total particles reaching each goal state');
        ylim(axesSplitNew,[0,100]);
        title(axesSplitNew,'Percentage of total particles reaching each goal state for different fluid velocities with user control starting in split formation');
        box(axesSplitNew,'on');
        grid(axesSplitNew,'on');
        legend(axesSplitNew,["Goal 1", "Goal 2", "Goal 3", "Goal 4", "Goal 5"],'Location','northwest');
        end
    end
 end
end