function plotResultsMAR23()
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 08-Apr-2022 11:27:04

close all;

x = 60:60:360;


yBENClump = [0 0 3 462.3 0;
1.4 0.4 2.7 423.1 35;
4.7 5.1 7.5 459.1 21.2;
9.1 11.3 13.9 377.3 85.6;
20.2 2.1 14.3 263.8 145.9;
27.5 3.8 13.9 271.2 160];

yBENSplit = [0.8 0 2.4 463 0.3;
22 1.6 0.1 443.4 14.2;
10.5 2.5 12.6 456.7 13.4;
33.5 4.3 12.8 361.1 54.6;
74 5.4 18.2 291.7 64;
125.2 17.5 9.3 216.8 84.5];
yBENClump = yBENClump./5;
yBENSplit = yBENSplit./5;

yBENClumpSummed = cumsum(yBENClump,2);
yBENSplitSummed = cumsum(yBENSplit,2);

%More Experiment Data:
yExperimentClump{1} = [0 0.45454545454545453 0.36363636363636365 487.1818181818182 0.2727272727272727;
12.333333333333334 5 0 364 84.22222222222223;
48.27272727272727 32.09090909090909 14 307.3636363636364 76.0909090909091;
47.142857142857146 139.71428571428572 3.857142857142857 176.57142857142858 129.71428571428572;
73.77777777777777 54.888888888888886 11.555555555555555 145.11111111111111 173.33333333333334;
56.5 64.125 19.5 139.875 205.5];

yExperimentSplit{1} = [0 0 0.25 439.75 7.625;
34.81818181818182 0 0.7272727272727273 459.27272727272725 4.636363636363637;
13.25 103.375 10.375 274 69.875;
39.84615384615385 124 4.384615384615385 221.69230769230768 95.07692307692308;
95.61538461538461 60.69230769230769 18.923076923076923 205.46153846153845 78.84615384615384;
116.08333333333333 98.83333333333333 15 126.58333333333333 85.83333333333333];

yExperimentClump{2} = [0 0.7 3.4 447 2;
50 0 0.3 336.5 104.2;
51.8 3.6 4 360.7 55.9;
65.3 9.5 0.7 178.9 244.6;
60.5 5.7 8.9 191.8 221.1;
68.2 4 4.8 189 230.3];

yExperimentSplit{2} = [3.4 0 6.2 357 69.9;
120.3 0 0.4 335.8 31.7;
132.9 0.9 4.7 330.1 27;
124.6 14.6 1.5 209.4 119.3;
110.1 17 2.5 213.3 120.9;
143.9 8.1 8.7 202.8 109];

yExperimentClump{3} = [0 0.1 0 440.2 9.7;
1.2 0.4 5 411 82.2;
11.7 37.6 9.3 348.1 92.8;
33 82.2 1.7 163.3 213.6;
52.6 35.1 13.1 171.2 204.9;
54.6 39.8 22.4 156.3 186.8];

yExperimentSplit{3} = [13.2 13.7 0.4 448.9 6.5;
13.7 16.6 3.5 406.1 46.3;
27.3 71.9 7.3 328.1 59;
38.9 61.8 18.9 248.5 121.4;
64.9 54.6 38.5 213 96.8;
69.3 77 23.9 210.7 97.4];

yExperimentClump{4} = [0.6 0 0 412.2 11.2;
18.3 0 2.2 338.8 140.4;
33.9 15.6 7.3 256.4 135.1;
35.2 40.8 1.7 164.7 252.9;
56 23.6 6 192.2 217;
41 28.9 8.1 163.8 220];

yExperimentSplit{4} = [0 0.1 0.8 383.6 13.3;
117.3 0 1.5 343.7 35.3;
97.7 9.7 1.7 304 38.5;
68.1 63.4 0.5 242.7 104.7;
106.7 25.3 3.1 251.2 86.9;
122.3 43 6.5 187.3 114.4];

%THIS ONE IS COMBINED
yExperimentClump{5} = [0.975609756097561 0.2926829268292683 2.4390243902439024 427.3414634146341 20.341463414634145;
53.89795918367347 1.836734693877551 2.2857142857142856 345.6530612244898 82.3061224489796;
60.666666666666664 15.137254901960784 7.470588235294118 266.72549019607845 120.92156862745098;
49.44444444444444 54.851851851851855 1.8888888888888888 173.03703703703704 217.88888888888889;
63.06896551724138 27.137931034482758 8.724137931034482 177.44827586206895 204.86206896551724;
55.142857142857146 30.071428571428573 10.178571428571429 165.96428571428572 219.53571428571428];

yExperimentSplit{5} = [36.1875 0.020833333333333332 1.6458333333333333 367.6458333333333 46.916666666666664;
91.33333333333333 4.7254901960784315 0.9607843137254902 308.4313725490196 85.49019607843137;
94.4375 21.958333333333332 5.875 259.3958333333333 95.97916666666667;
74.0909090909091 72.48484848484848 2.3333333333333335 224.33333333333334 105.33333333333333;
103.36363636363636 36.72727272727273 9.151515151515152 221.6969696969697 94.03030303030303;
126.71875 53.03125 10.375 169.375 102];



%Now draw the data:

% Create figure
figure1 = figure;
figure2 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');
axes2 = axes('Parent',figure2);
hold(axes2,'on');

plot1 = plot(axes1,x,yBENClump, '.-','MarkerSize',4,'MarkerFaceColor','#ff3300');
plot2 = plot(axes2,x,yBENSplit, '.-','MarkerSize',4,'MarkerFaceColor','#ff3300');

set(plot1(1),'DisplayName','Goal 1');
set(plot1(2),'DisplayName','Goal 2');
set(plot1(3),'DisplayName','Goal 3');
set(plot1(4),'DisplayName','Goal 4');
set(plot1(5),'DisplayName','Goal 5');
xlabel(axes1,"Maximum Fluid Velocity (mm/s)");
ylabel(axes1, 'Percentage of particles reaching each goal state');
title(axes1,'Percentage of particles reaching each goal state for different fluid velocities starting in a clump formation');
box(axes1,'on');
grid(axes1,'on');
legend(axes1,'show','Location','northeast');

set(plot2(1),'DisplayName','Goal 1');
set(plot2(2),'DisplayName','Goal 2');
set(plot2(3),'DisplayName','Goal 3');
set(plot2(4),'DisplayName','Goal 4');
set(plot2(5),'DisplayName','Goal 5');
xlabel(axes2,"Maximum Fluid Velocity (mm/s)");
ylabel(axes2, 'Percentage of particles reaching each goal state');
title(axes2,'Percentage of particles reaching each goal state for different fluid velocities starting in a split formation');
box(axes2,'on');
grid(axes2,'on');
legend(axes2,'show','Location','northeast');


 for(i = 1:size(yExperimentClump,2))
    % Create figure
    figureClumpNew = figure; 
    figureSplitNew = figure;

    %Create axes
    axesClumpNew = axes('Parent',figureClumpNew);
    hold(axesClumpNew,'on');
    axesSplitNew = axes('Parent',figureSplitNew);
    hold(axesSplitNew,'on');


    if(true)

        %Both bar charts
        barPlotClump = bar(axesClumpNew, x-12.5, yExperimentClump{i}./5,0.4, "stacked");
        barPlotSplit = bar(axesSplitNew, x-12.5, yExperimentSplit{i}./5,0.4, "stacked");
        barPlotClumpB = bar(axesClumpNew, x+12.5, yBENClump,0.4, "stacked");
        barPlotSplitB = bar(axesSplitNew, x+12.5, yBENSplit,0.4, "stacked");
        set(barPlotClumpB(1),'FaceColor','blue');
        set(barPlotClumpB(2),'FaceColor','red');
        set(barPlotClumpB(3),'FaceColor','yellow');
        set(barPlotClumpB(4),'FaceColor','magenta');
        set(barPlotClumpB(5),'FaceColor','green');
        set(barPlotSplitB(1),'FaceColor','blue');
        set(barPlotSplitB(2),'FaceColor','red');
        set(barPlotSplitB(3),'FaceColor','yellow');
        set(barPlotSplitB(4),'FaceColor','magenta');
        set(barPlotSplitB(5),'FaceColor','green');
        hold on;

        set(barPlotClump(1),'DisplayName','Goal 1');
        set(barPlotClump(2),'DisplayName','Goal 2');
        set(barPlotClump(3),'DisplayName','Goal 3');
        set(barPlotClump(4),'DisplayName','Goal 4');
        set(barPlotClump(5),'DisplayName','Goal 5');
        set(barPlotSplit(1),'DisplayName','Goal 1');
        set(barPlotSplit(2),'DisplayName','Goal 2');
        set(barPlotSplit(3),'DisplayName','Goal 3');
        set(barPlotSplit(4),'DisplayName','Goal 4');
        set(barPlotSplit(5),'DisplayName','Goal 5');
        set(barPlotClumpB(1),'DisplayName','Goal 1 (Ex)');
        set(barPlotClumpB(2),'DisplayName','Goal 2 (Ex)');
        set(barPlotClumpB(3),'DisplayName','Goal 3 (Ex)');
        set(barPlotClumpB(4),'DisplayName','Goal 4 (Ex)');
        set(barPlotClumpB(5),'DisplayName','Goal 5 (Ex)');
        set(barPlotSplitB(1),'DisplayName','Goal 1 (Ex)');
        set(barPlotSplitB(2),'DisplayName','Goal 2 (Ex)');
        set(barPlotSplitB(3),'DisplayName','Goal 3 (Ex)');
        set(barPlotSplitB(4),'DisplayName','Goal 4 (Ex)');
        set(barPlotSplitB(5),'DisplayName','Goal 5 (Ex)');

        xlabel(axesClumpNew,"Maximum Fluid Velocity (mm/s)");
        ylabel(axesClumpNew, 'Percentage of particles reaching each goal state');
        title(axesClumpNew,'Percentage of particles reaching each goal state for different fluid velocities starting in a clump formation');
        box(axesClumpNew,'on');
        grid(axesClumpNew,'on');
        legend(axesClumpNew,'show','Location','southwest');

        xlabel(axesSplitNew,"Maximum Fluid Velocity (mm/s)");
        ylabel(axesSplitNew, 'Percentage of particles reaching each goal state');
        title(axesSplitNew,'Percentage of particles reaching each goal state for different fluid velocities starting in a split formation');
        box(axesSplitNew,'on');
        grid(axesSplitNew,'on');
        legend(axesSplitNew,'show','Location','southwest');
    else
        if(true)
            barPlotClump = bar(axesClumpNew, x, yExperimentClump{i}./5, "stacked");
            barPlotSplit = bar(axesSplitNew, x, yExperimentSplit{i}./5, "stacked");
            plotBenClumpCumulative = plot(axesClumpNew,x,yBENClumpSummed, '.-','MarkerSize',4,'MarkerFaceColor','#ff3300');
            plotBenSplitCumulative = plot(axesSplitNew,x,yBENSplitSummed, '.-','MarkerSize',4,'MarkerFaceColor','#ff3300');
        else
        %plot
        plotNewClump = plot(axesClumpNew,x,yExperimentClump{i}./5, '.-','MarkerSize',4,'MarkerFaceColor','green');
        xlabel(axesClumpNew,"Maximum Fluid Velocity (mm/s)");
        ylabel(axesClumpNew, 'Percentage of total particles reaching each goal state');
        ylim(axesClumpNew,[0,100]);
        title(axesClumpNew,'Percentage of total particles reaching each goal state for different fluid velocities with user control starting in clump formation');
        box(axesClumpNew,'on');
        grid(axesClumpNew,'on');
        legend(axesClumpNew,["Goal 1", "Goal 2", "Goal 3", "Goal 4", "Goal 5"],'Location','northwest');
    
        plotNewSplit = plot(axesSplitNew,x,yExperimentSplit{i}./5, '.-','MarkerSize',4,'MarkerFaceColor','green');
        xlabel(axesSplitNew,"Maximum Fluid Velocity (mm/s)");
        ylabel(axesSplitNew, 'Percentage of total particles reaching each goal state');
        ylim(axesSplitNew,[0,100]);
        title(axesSplitNew,'Percentage of total particles reaching each goal state for different fluid velocities with user control starting in split formation');
        box(axesSplitNew,'on');
        grid(axesSplitNew,'on');
        legend(axesSplitNew,["Goal 1", "Goal 2", "Goal 3", "Goal 4", "Goal 5"],'Location','northwest');
        end
    end
 end
end